name: Build and Scan Image

on: 
  push:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull vulnerable image
      run: docker pull owasp/broken-web-app:latest

    - name: Set up Clair
      run: |
        mkdir report
        docker run -d --name clair-db arminc/clair-db:latest
        docker run -p 6060:6060 --link clair-db:postgres -d --name clair arminc/clair-local-scan:latest
        sleep 10
        CLAIR_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' clair)
        docker pull jitesoft/clair-scanner:latest

    - name: Scan image with Clair
      run: docker run --network host -v /var/run/docker.sock:/var/run/docker.sock jitesoft/clair-scanner:latest --clair=http://$CLAIR_IP:6060 owasp/broken-web-app:latest

    - name: Stop and remove Clair
      run: |
        docker stop clair
        docker rm clair
        docker stop clair-db
        docker rm clair-db

    - name: Publish vulnerabilities report
      uses: actions/upload-artifact@v2
      with:
        name: VulnerabilitiesReport
        path: report

